### ISSUE TITLE
MMP12_experiments.ipynb error : has no "mol1"

### ISSUE THREAD

**Issue by cgh2797** [maxime-langevin/scaffold-constrained-generation#2]
![캡처saas](https://user-images.githubusercontent.com/19909579/94385970-67dedd80-0181-11eb-9f35-e053360c6936.PNG)
why there's no mol1??

**Comment by maxime-langevin** [comment]
Hello Geunho,
My bad for this mistake. This part of the code for just there to align the molecule drawn (m2) with a previously draw molecule (m1) in order to get a decent figure for the paper, and doesn't not serves any other purpose. I removed it as it is not necessary to reproduce the resultds from the paper and adds unnecessary complexity. 
Best,
Maxime
